-- ============================================================
-- TOUCANTRIALS DATABASE
-- ============================================================

-- ============================================================
-- PROFILES
-- ============================================================

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,

    username text not null,

    total_coins integer not null default 0
        check (total_coins >= 0),

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now()
);


-- ============================================================
-- RUNS
-- ============================================================

create table if not exists public.runs (
    id bigint generated by default as identity primary key,

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    level_id text not null,

    completion_time_ms bigint
        check (
            completion_time_ms is null
            or completion_time_ms >= 0
        ),

    coins_collected integer not null default 0
        check (coins_collected >= 0),

    completed boolean not null default false,

    created_at timestamptz not null default now()
);


-- ============================================================
-- INDEXES
-- ============================================================

create index if not exists runs_user_id_idx
on public.runs(user_id);

create index if not exists runs_level_id_idx
on public.runs(level_id);

create index if not exists runs_user_level_idx
on public.runs(user_id, level_id);


-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table public.profiles enable row level security;

alter table public.runs enable row level security;


-- ============================================================
-- PROFILE POLICIES
-- ============================================================

drop policy if exists "Users can view their own profile"
on public.profiles;

create policy "Users can view their own profile"
on public.profiles
for select
using (
    auth.uid() = id
);


drop policy if exists "Users can update their own profile"
on public.profiles;

create policy "Users can update their own profile"
on public.profiles
for update
using (
    auth.uid() = id
)
with check (
    auth.uid() = id
);


-- ============================================================
-- RUN POLICIES
-- ============================================================

drop policy if exists "Users can view their own runs"
on public.runs;

create policy "Users can view their own runs"
on public.runs
for select
using (
    auth.uid() = user_id
);


drop policy if exists "Users can create their own runs"
on public.runs;

create policy "Users can create their own runs"
on public.runs
for insert
with check (
    auth.uid() = user_id
);


-- ============================================================
-- AUTO-CREATE PROFILE WHEN USER SIGNS UP
-- ============================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin

    insert into public.profiles (
        id,
        username
    )

    values (
        new.id,

        coalesce(
            new.raw_user_meta_data ->> 'username',
            split_part(new.email, '@', 1),
            'Player'
        )
    );

    return new;

end;
$$;


-- ============================================================
-- AUTH USER → PROFILE TRIGGER
-- ============================================================

drop trigger if exists on_auth_user_created
on auth.users;

create trigger on_auth_user_created

after insert on auth.users

for each row

execute procedure public.handle_new_user();